services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: feedfusion-container
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      GETFEEDS: 30
      SCRAPETEXT: 15
      SCRAPEDOM: 20
    volumes:
      - ~/ff_data:/app/data
      - ~/ff_data/dom:/app/data/dom